### PR TITLE
Goroutine limit feature

### PR DESCRIPTION
**Pull request by cowtoolz**
This is literally just #9 with the requested changes. Let me know if you want me to squash before merging.

Closes #9

### CODE REVIEW

**Comment by saracen** [comment]
I merged #9 with the hope this would automatically update and drop the first commit/diff between the new master, but it doesn't look like it has.

Can you update this PR dropping the first commit and then I'll merge. Thank you for this!

**Comment by cowtoolz** [comment]
Done, appreciate the quick turnaround.

**Comment by cowtoolz** [comment]
cc @saracen

**Comment by saracen** [comment]
@weebney Thanks for the ping, I'd missed the notification for the last message. Sorry about that!

**Pull request merged**
