### PR TITLE
Walk root directory if it's a symlink to a directory

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
Gentle ping @saracen :-)

**Comment by lebauce** [comment]
@saracen Could you please have a look at my PR ? Thanks !

**Comment by saracen** [comment]
Hey @lebauce,

I'm not sure about adding this, as similar to Go's filepath.Walk, this doesn't follow symlinks. I'm not sure the root dir makes this an exceptional case or not though.

**Comment by lebauce** [comment]
@saracen This is to support walking /proc/self/root : you need to readdir it directly (following it and then doing a readdir can't work)

**Comment by lebauce** [comment]
@saracen Could you please take an other look ? I tried to advocate for the following of root dirs in my previous comment :-)

**Pull request closed without merging**
